### PR TITLE
Update runtime to 5.15-21.08

### PR DESCRIPTION
**Pull request by hfiguiere**
5.15 is EOL

### CODE REVIEW

**Comment by hfiguiere** [comment]
works fine here.

**Comment by tooomm** [comment]
>works fine here.

Thanks for your PR @hfiguiere! That's very much appreciated. 👍 

Can you let me know where to check those lifecycles and learn about the various versions, please?

**Comment by hfiguiere** [comment]
it in the discourse forums, at least.

https://discourse.flathub.org/t/kde-runtimes-5-15-21-08-and-6-2-released/1936

**Comment by tooomm** [comment]
Thank you!

**Pull request merged**
