### PR TITLE
update to 2.6.1

### PR DESCRIPTION
**Pull request by tooomm**
https://github.com/Cockatrice/Cockatrice/releases/tag/2018-07-17-Release-2.6.1

### CODE REVIEW

**Comment by barthalion** [comment]
@subpop, what do you think about giving @tooomm push access?

**Comment by barthalion** [comment]
It fails to build: https://flathub.org/builds/#/builders/40/builds/272

**Comment by subpop** [comment]
The line that is failing:

```
FB: Running: flatpak build --die-with-parent --nofilesystem=host --filesystem=/home/builder/worker-new/build-aarch64-5/io.github.Cockatrice.cockatrice/.flatpak-builder/build/cockatrice-1 --bind-mount=/run/build/cockatrice=/home/builder/worker-new/build-aarch64-5/io.github.Cockatrice.cockatrice/.flatpak-builder/build/cockatrice-1 --build-dir=/run/build/cockatrice --bind-mount=/run/ccache=/home/builder/worker-new/build-aarch64-5/io.github.Cockatrice.cockatrice/.flatpak-builder/ccache --unshare=network --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=8 /home/builder/worker-new/build-aarch64-5/io.github.Cockatrice.cockatrice/.flatpak-builder/rofiles/rofiles-3OYUyv /bin/sh -c 'for size in 64 128; do rsvg-convert -w $size -h $size -f png -o $size.png /app/share/icons/hicolor/scalable/apps/cockatrice.svg install -Dm644 $size.png /app/share/icons/hicolor/${size}x${size}/apps/cockatrice.png done'
/bin/sh: -c: line 1: syntax error: unexpected end of file
```

`unexpected end of file` makes me think the scalable svg might be messed up?

**Comment by tooomm** [comment]
Hmm, `cockatrice.svg` and `cockatrice.png` files hasn't changed in the last 3 years...
https://github.com/Cockatrice/Cockatrice/tree/master/cockatrice/resources

**Pull request merged**
