### PR TITLE
Update runtime to 6.6

### LINKED ISSUE #41: Potentially unsafe: Legacy windowing system
Just realized this rankings on the new Flathub site...
image

<br>

Why is this legacy warning shown and how can we solve it?

### PR DESCRIPTION
**Pull request by hfiguiere**
- Also modernize the manifest a bit
- expand the cleanup rules

Coincidentally close #41

### CODE REVIEW

**Comment by hfiguiere** [comment]
this linting should be done upstream, but ok. (yes including hosting the appstream file there)

**Comment by tooomm** [comment]
Hi! :) 
Thanks for your PR and the updates you provided. Very much appreciated!

Can you please confirm the resulting test file works for you as well?

A linting check is done upstream too, just at a late stage and you don't get a quick result.
Or did I get your comment wrong?

**Comment by hfiguiere** [comment]
> Can you please confirm the resulting test file works for you as well?

which file?

> 
> A linting check is done upstream too, just at a late stage and you don't get a quick result. Or did I get your comment wrong?

if it's done upstream that mean the appstream file is upstream. so why is it still here?

**Comment by tooomm** [comment]
>which file?

The test build provided e.g. here: https://github.com/flathub/io.github.Cockatrice.cockatrice/pull/55#issuecomment-1908957626

>if it's done upstream that mean the appstream file is upstream. so why is it still here?

I'm not sure we are on the same page here, can you please elaborate?
I was referring to the Flathub CI build system. They at least used to include to check the files for linting errors. Maybe see the PR introducing the workflow.

**Comment by hfiguiere** [comment]
I ran the build locally if that's what you meant. Seems to work ok.

> Can you please confirm the resulting test file works for you as well?

"test file" is what confused me. It's not a test file.

My thought is the appstream SHOULD be managed upstream. I know it has been like that forever, but that's not the best practice at all.

**Comment by tooomm** [comment]
>I ran the build locally if that's what you meant. Seems to work ok.

I was referring to the file produced by the Flathub build system (see https://github.com/flathub/io.github.Cockatrice.cockatrice/pull/55#issuecomment-1908957626) and which is intended for testing. Wanted to know if you gave that a try. :)

Did you also install the new build hosted on Flathub after your changes and it works smoothly?

<br>

>My thought is the appstream SHOULD be managed upstream. I know it has been like that forever, but that's not the best practice at all.

Not sure we are on the same page.
Upstream you mean the Cockatrice repo? I was referring to Flathub and their build system when replying to your linting comment.

**Pull request merged**
