### PR TITLE
 implement release version number + date

### PR DESCRIPTION
**Pull request by tooomm**
Match https://github.com/flathub/io.github.Cockatrice.cockatrice/blob/master/io.github.Cockatrice.cockatrice.json#L49

Currently this information isn't shown at https://flathub.org/apps/details/io.github.Cockatrice.cockatrice

---

Change according to https://github.com/flathub/io.github.Cockatrice.cockatrice/pull/3#issuecomment-357711235

### CODE REVIEW

**Comment by TingPing** [comment]
Have you tried getting this upstream yet?

**Comment by TingPing** [comment]
Getting the appdata file maintained by cockatrice

**Comment by subpop** [comment]
Yea, it's on my todo list (to submit a PR upstream that adds the AppData and necessary code to install it to the CMakeList.txt files). I've just not gotten around to it.

**Comment by tooomm** [comment]
For now we might still want to merge this to get that info on the official page:
https://flathub.org/apps/details/io.github.Cockatrice.cockatrice

At one point it would be great to have it included, sure. 👍

**Comment by nedrichards** [comment]
bot, build

**Comment by subpop** [comment]
This looks ready to merge (despite an imminent upgrade to 2.7.0). @tooomm?

**Comment by tooomm** [comment]
We could merge this for now and see if it works.

An upgrade to 2.7.0 will happen soonish I guess, @ebbit1q's fix should work fine.

**Pull request merged**
