### PR TITLE
bump to 2.7.0

### PR DESCRIPTION
**Pull request by tooomm**
https://github.com/Cockatrice/Cockatrice/releases/tag/2019-03-04-Release-2.7.0

### CODE REVIEW

**Comment by tooomm** [comment]
Can you have a look please @subpop?

**Comment by subpop** [comment]
Hmm, at first glance, it looks like an API change. Did the minimum Qt version requirement change?

```
/run/build/cockatrice/common/expression.cpp: In constructor ‘Expression::Expression(double)’:
/run/build/cockatrice/common/expression.cpp:41:73: error: no matching function for call to ‘QMap<QString, std::function<double(double)> >::insert(const char [4], Expression::Expression(double)::<lambda(double)>)’
         default_functions->insert("abs", [](double a) { return abs(a); });
                                                                         ^
In file included from /usr/include/QtCore/QMap:1:0,
                 from /run/build/cockatrice/common/expression.h:4,
                 from /run/build/cockatrice/common/expression.cpp:1:
/usr/include/QtCore/qmap.h:694:51: note: candidate: QMap<K, V>::iterator QMap<K, V>::insert(const Key&, const T&) [with Key = QString; T = std::function<double(double)>]
 Q_INLINE_TEMPLATE typename QMap<Key, T>::iterator QMap<Key, T>::insert(const Key &akey, const T &avalue)
                                                   ^~~~~~~~~~~~
/usr/include/QtCore/qmap.h:694:51: note:   no known conversion for argument 2 from ‘Expression::Expression(double)::<lambda(double)>’ to ‘const std::function<double(double)>&’
/usr/include/QtCore/qmap.h:721:33: note: candidate: QMap<K, V>::iterator QMap<K, V>::insert(QMap<K, V>::const_iterator, const Key&, const T&) [with Key = QString; T = std::function<double(double)>]
 typename QMap<Key, T>::iterator QMap<Key, T>::insert(const_iterator pos, const Key &akey, const T &avalue)
                                 ^~~~~~~~~~~~
```

**Comment by tooomm** [comment]
Minimum Qt version is Qt 5.5.0, which was the same in 2.6.2 release.

But this will change to Qt 5.9 LTS soon (Qt 5.9.7).
All the binaries we provide use 5.9 or 5.12 already.

**Comment by subpop** [comment]
Ok. I dug back further in the build log and noticed this:

```
/run/build/cockatrice/common/expression.cpp:41:69: error: call of overloaded ‘abs(double&)’ is ambiguous
         default_functions->insert("abs", [](double a) { return abs(a); });
```

If cockatrice were built with all warnings being treated as errors, I could see that happening. Any idea if that is a valid error/warning?

**Comment by ebbit1q** [comment]
That is in no way a valid error, abs(double) is perfectly there, included by cmath, not to mention that the surrounding lines use other std cmath functions like sqrt, log, and trunc.

**Comment by subpop** [comment]
@toomm, with #18 merged, can you rebase this on `master` to trigger another build?

**Pull request merged**
