### PR TITLE
Update appdata.xml

### PR DESCRIPTION
**Pull request by tooomm**
- New app id

    `appstreamcli validate` gave me:
    >W: cockatrice.desktop:3: cid-desktopapp-is-not-rdns cockatrice.desktop

    The Flathub validate is not complaining, but the docs tell the same:
    [`<id>`](https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/#id): [Each application should have a unique application ID, following the standard reverse-DNS schema](https://docs.flathub.org/docs/for-app-authors/requirements#application-id)

<br>

- New component header according to https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/#header

<br>

- Fixing appstreamcli warning
    > `W: io.github.Cockatrice.cockatrice:59: circular-component-relation`

    The Flathub validate is also not complaining here.

<br>

- Referencing old name

### CODE REVIEW

**Comment by tooomm** [comment]
Hi @TingPing, can you please check and verify here that the app id change etc. are not problematic?

**Comment by TingPing** [comment]
The app id change is correct.

I would add this though:

```xml
  <provides>
    <!-- Renamed from this -->
    <id>cockatrice.desktop</id>
  </provides>
```

**Comment by tooomm** [comment]
Cool, thanks for the review and note. Makes me feel more safe about this. 😀

Wondering though why the internal appdata validation in your buildbot instance is not complaining. Also unsure what the actual changes for Flathub's own AppStream tool are (which is recommended in the docs but can not be used in GitHub Actions).

**Comment by TingPing** [comment]
I believe Flathub still uses `appstream-util`, which is deprecated in favor of `appstreamcli`, so it has different output and is sometimes worse.

The patches it has are here: https://github.com/flathub/org.freedesktop.appstream-glib/tree/master/patches

You can just install `org.freedesktop.appstream-glib`.

**Comment by tooomm** [comment]
> I believe Flathub still uses `appstream-util`, which is deprecated in favor of `appstreamcli`, so it has different output and is sometimes worse.

Correct! Just checked the logs.

> The patches it has are here: https://github.com/flathub/org.freedesktop.appstream-glib/tree/master/patches
> 
> You can just install `org.freedesktop.appstream-glib`.

That's great information!
But I guess going with the newer, default appstreamcli (v0.16.2) is also fine unless I missed an important detail.

**Comment by TingPing** [comment]
>  But I guess going with the newer, default appstreamcli (v0.16.2) is also fine unless I missed an important detail.

Should be fine. Flathub has been working on moving to it for a while, will happen eventually.

**Pull request merged**
